# Generated by Django 4.1.1 on 2023-04-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.TextField()),
                ('allergies', models.TextField()),
                ('is_safeforchild', models.BooleanField(default=True)),
                ('note', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
