# Generated by Django 4.1.1 on 2022-10-28 07:09

import DOCTER.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0002_appointment_cancellation_reason_and_more'),
        ('PATIENT', '0002_patient_dob_patient_allergies_and_more'),
        ('DOCTER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='docter',
            name='average_appointment_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='docter',
            name='average_fee',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='docter',
            name='category',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='blood_pressure',
            field=models.CharField(blank=True, default='Normal', max_length=30),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='diet',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription2',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='pulse_rate',
            field=models.IntegerField(blank=True, default=72),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='docter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='docter',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(max_length=2)),
                ('doctor', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter', unique=True)),
                ('patient', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='medreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment')),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
        migrations.CreateModel(
            name='blocktime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField(default=DOCTER.models.in_30_days)),
                ('reason', models.TextField(default='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter')),
            ],
        ),
        migrations.AddField(
            model_name='docter',
            name='specialization',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.specialization'),
        ),
    ]
