# Generated by Django 4.1.1 on 2023-04-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('chemist', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.chemist')),
                ('medicine', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.medicine')),
            ],
        ),
    ]
