# Generated by Django 4.1.1 on 2023-04-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0003_chemistmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistmedicine',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
