# Generated by Django 4.1 on 2022-09-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0003_patient_dob_patient_disability_and_more'),
        ('COMMON_APP', '0004_appointment_note'),
        ('DOCTER', '0003_alter_docter_email_alter_docter_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='category',
            field=models.CharField(default='MBBS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription2',
            name='blood_pressure',
            field=models.CharField(blank=True, default='Normal', max_length=30),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='pulse_rate',
            field=models.IntegerField(blank=True, default=72),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='docter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='docter',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='medreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment')),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
