# Generated by Django 4.1 on 2022-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0004_docter_category_prescription2_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription2',
            name='diet',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
