# Generated by Django 4.1 on 2022-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0005_prescription2_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='specialization',
            field=models.CharField(default='general', max_length=20),
            preserve_default=False,
        ),
    ]
