# Generated by Django 4.1.1 on 2022-09-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0007_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docter',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.specialization'),
        ),
    ]
