# Generated by Django 4.1.1 on 2022-09-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0011_alter_docter_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docter',
            name='specialization',
        ),
    ]
