# Generated by Django 4.1.1 on 2022-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0014_specialization_docter_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
