# Generated by Django 4.1.1 on 2022-10-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0015_docter_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='everage_fee',
            field=models.IntegerField(default=500),
        ),
    ]
