# Generated by Django 4.1.1 on 2022-10-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0003_patient_dob_patient_disability_and_more'),
        ('DOCTER', '0017_rename_everage_fee_docter_average_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='docter',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docter',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(max_length=2)),
                ('doctor', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter', unique=True)),
                ('patient', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient', unique=True)),
            ],
        ),
    ]
