# Generated by Django 4.1.1 on 2022-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_diseases',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medicines',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='diet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='disability',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='male', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='case',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
