# Generated by Django 4.1 on 2022-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0002_alter_patient_email_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='disability',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance_no',
            field=models.CharField(default='12345', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Male', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
