# Generated by Django 4.1.1 on 2022-10-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0002_patient_dob_patient_allergies_and_more'),
        ('DOCTER', '0001_initial'),
        ('COMMON_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_doct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='docterid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_pop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(default='1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='share_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
