# Generated by Django 4.1.1 on 2023-04-04 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DOCTER', '0001_initial'),
        ('COMMON_APP', '0001_initial'),
        ('PATIENT', '0002_patient_dob_patient_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointpath',
            name='pathologist',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.pathologist'),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='appointment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment'),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.test'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='blogid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.blog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='docterid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter'),
        ),
        migrations.AddField(
            model_name='notification',
            name='patientid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
        migrations.AddField(
            model_name='hr',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemistappointment',
            name='appointment',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment'),
        ),
        migrations.AddField(
            model_name='chemistappointment',
            name='chemist',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.chemist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='docterid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
    ]
