# Generated by Django 4.1.1 on 2023-04-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0001_initial'),
        ('COMMON_APP', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='pathologist',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.pathologist'),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.DeleteModel(
            name='TestAppointPath',
        ),
    ]
