# Generated by Django 4.1.1 on 2023-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0006_chemist'),
        ('PATIENT', '0002_patient_dob_patient_allergies_and_more'),
        ('COMMON_APP', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='blogid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.blog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='docterid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='patientid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
        migrations.CreateModel(
            name='ChemistAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('medicinelist', models.TextField()),
                ('appointment', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment')),
                ('chemist', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.chemist')),
            ],
        ),
    ]
