# Generated by Django 4.1.1 on 2023-04-05 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0002_medicine'),
        ('COMMON_APP', '0003_testappointment_pathologist_testappointment_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=500)),
                ('dailytime', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=0)),
                ('fordays', models.IntegerField(default=7)),
                ('eachdosequantity', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.appointment')),
                ('chemist', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.chemist')),
                ('medicine', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.medicine')),
            ],
        ),
    ]
