# Generated by Django 4.1.1 on 2023-04-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCTER', '0002_medicine'),
        ('PATIENT', '0002_patient_dob_patient_allergies_and_more'),
        ('COMMON_APP', '0004_medicineappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DOCTER.docter')),
                ('patient', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
            ],
        ),
    ]
