# Generated by Django 4.1 on 2022-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0004_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='share_permission',
            field=models.BooleanField(default=True),
        ),
    ]
