# Generated by Django 4.1.1 on 2023-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0004_notification_appointment_notification_blogid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_patient',
            field=models.BooleanField(default=False),
        ),
    ]
