# Generated by Django 4.1.1 on 2023-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0005_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pattodoct',
            field=models.BooleanField(default=True),
        ),
    ]
