# Generated by Django 4.1.1 on 2023-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0006_chat_pattodoct'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineappointment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
