# Generated by Django 4.1.1 on 2023-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0007_medicineappointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistappointment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
