# Generated by Django 4.1.1 on 2023-04-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0008_chemistappointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='reporturl',
            field=models.TextField(blank=True, default=''),
        ),
    ]
